user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzc5NzM=

session:
  key: oylXm_IwP0he6FmKvvTthGZQBSWtcL-gBoxs8s5kN_Q=
admin:
  email: admin@admin.com
  password: admin
bot:
  token: group_token
  group_id: 1


